const data = {
    "countryToCode": {
        "Afghanistan": ["93"],
        "Albanien": ["355"],
        "Algerien": ["213"],
        "Andorra": ["376"],
        "Angola": ["244"],
        "Antarktis": ["672"],
        "Norfolk": ["672"],
        "Antigua und Barbuda": ["1268"],
        "Äquatorial-Guinea": ["240"],
        "Argentinien": ["54"],
        "Armenien": ["374"],
        "Aserbaidschan": ["994"],
        "Australien": ["61"],
        "Bangladesh": ["880"],
        "Belgien": ["32"],
        "Bolivien": ["591"],
        "Bosnien-Herzegowina": ["387"],
        "Brasilien": ["55"],
        "Bulgarien": ["359"],
        "Kambodscha": ["855"],
        "Kamerun": ["237"],
        "Kap Verde": ["238"],
        "Zentralafrikanische Republik": ["236"],
        "Chile": ["56"],
        "China": ["86"],
        "Kolumbien": ["57"],
        "Kongo": ["242"],
        "Kongo, Demokratische Republik": ["243"],
        "Costa Rica": ["506"],
        "Elfenbeinküste": ["225"],
        "Kroatien": ["385"],
        "Kuba": ["53"],
        "Tschechische Republik": ["420"],
        "Dänemark": ["45"],
        "Dominikanische Republik": ["1809"],
        "Ecuador": ["593"],
        "Ägypten": ["20"],
        "El Salvador": ["503"],
        "Estland": ["372"],
        "Färöer-Inseln": ["298"],
        "Fidschi": ["679"],
        "Finnland": ["358"],
        "Frankreich": ["33"],
        "Französisch-Guayana": ["594"],
        "Georgien": ["995"],
        "Deutschland": ["49"],
        "Ghana": ["233"],
        "Gibraltar": ["350"],
        "Griechenland": ["30"],
        "Grönland": ["299"],
        "Guatemala": ["502"],
        "Haiti": ["509"],
        "Honduras": ["504"],
        "Hongkong": ["852"],
        "Ungarn": ["36"],
        "Island": ["354"],
        "Indien": ["91"],
        "Indonesien": ["62"],
        "Iran": ["98"],
        "Irak": ["964"],
        "Irland": ["353"],
        "Israel": ["972"],
        "Italien": ["39"],
        "Jamaika": ["1876"],
        "Japan": ["81"],
        "Kenia": ["254"],
        "Kirgisistan": ["996"],
        "Laos": ["856"],
        "Lettland": ["371"],
        "Libanon": ["961"],
        "Lesotho": ["266"],
        "Liberia": ["231"],
        "Libyen": ["218"],
        "Liechtenstein": ["423"],
        "Litauen": ["370"],
        "Luxemburg": ["352"],
        "Nordmazedonien": ["389"],
        "Madagaskar": ["261"],
        "Malaysia": ["60"],
        "Malta": ["356"],
        "Mexiko": ["52"],
        "Moldawien": ["373"],
        "Monaco": ["377"],
        "Mongolei": ["976"],
        "Montenegro": ["382"],
        "Marokko": ["212"],
        "Myanmar": ["95"],
        "Namibia": ["264"],
        "Nepal": ["977"],
        "Niederlande": ["31"],
        "Neuseeland": ["64"],
        "Nicaragua": ["505"],
        "Niger": ["227"],
        "Nigeria": ["234"],
        "Norwegen": ["47"],
        "Pakistan": ["92"],
        "Panama": ["507"],
        "Papua-Neuguinea": ["675"],
        "Paraguay": ["595"],
        "Peru": ["51"],
        "Philippinen": ["63"],
        "Polen": ["48"],
        "Portugal": ["351"],
        "Rumänien": ["40"],
        "Russland": ["7"],
        "Kasachstan": ["7"],
        "San Marino": ["378"],
        "Saudi-Arabien": ["966"],
        "Senegal": ["221"],
        "Serbien": ["381"],
        "Seychellen": ["248"],
        "Singapur": ["65"],
        "Slowakei": ["421"],
        "Slowenien": ["386"],
        "Salomonen": ["677"],
        "Somalia": ["252"],
        "Südafrika": ["27"],
        "Südkorea": ["82"],
        "Südsudan": ["211"],
        "Spanien": ["34"],
        "Sri Lanka": ["94"],
        "Sudan": ["249"],
        "Suriname": ["597"],
        "Eswatini": ["268"],
        "Schweden": ["46"],
        "Schweiz": ["41"],
        "Syrien": ["963"],
        "Taiwan": ["886"],
        "Tadschikistan": ["992"],
        "Tansania": ["255"],
        "Thailand": ["66"],
        "Tunesien": ["216"],
        "Türkei": ["90"],
        "Turkmenistan": ["993"],
        "Uganda": ["256"],
        "Ukraine": ["380"],
        "Vereinigte Arabische Emirate": ["971"],
        "Vereinigtes Königreich": ["44"],
        "Vereinigte Staaten": ["1"],
        "Puerto Rico": ["1"],
        "Kanada": ["1"],
        "Uruguay": ["598"],
        "Usbekistan": ["998"],
        "Venezuela": ["58"],
        "Vietnam": ["84"],
        "Jemen": ["967"],
        "Sambia": ["260"],
        "Zimbabwe": ["263"],
        "Simbabwe": ["263"],
        "Zypern": ["357"]
    },
    "codeToCountry": {
        "93": ["Afghanistan"],
        "355": ["Albanien"],
        "213": ["Algerien"],
        "376": ["Andorra"],
        "244": ["Angola"],
        "672": ["Antarktis", "Norfolk"],
        "1268": ["Antigua und Barbuda"],
        "240": ["Äquatorial-Guinea"],
        "54": ["Argentinien"],
        "374": ["Armenien"],
        "994": ["Aserbaidschan"],
        "61": ["Australien"],
        "880": ["Bangladesh"],
        "32": ["Belgien"],
        "591": ["Bolivien"],
        "387": ["Bosnien-Herzegowina"],
        "55": ["Brasilien"],
        "359": ["Bulgarien"],
        "855": ["Kambodscha"],
        "237": ["Kamerun"],
        "238": ["Kap Verde"],
        "236": ["Zentralafrikanische Republik"],
        "56": ["Chile"],
        "86": ["China"],
        "57": ["Kolumbien"],
        "242": ["Kongo"],
        "243": ["Kongo, Demokratische Republik"],
        "506": ["Costa Rica"],
        "225": ["Elfenbeinküste"],
        "385": ["Kroatien"],
        "53": ["Kuba"],
        "420": ["Tschechische Republik"],
        "45": ["Dänemark"],
        "1809": ["Dominikanische Republik"],
        "593": ["Ecuador"],
        "20": ["Ägypten"],
        "503": ["El Salvador"],
        "372": ["Estland"],
        "298": ["Färöer-Inseln"],
        "679": ["Fidschi"],
        "358": ["Finnland"],
        "33": ["Frankreich"],
        "594": ["Französisch-Guayana"],
        "995": ["Georgien"],
        "49": ["Deutschland"],
        "233": ["Ghana"],
        "350": ["Gibraltar"],
        "30": ["Griechenland"],
        "299": ["Grönland"],
        "502": ["Guatemala"],
        "509": ["Haiti"],
        "504": ["Honduras"],
        "852": ["Hongkong"],
        "36": ["Ungarn"],
        "354": ["Island"],
        "91": ["Indien"],
        "62": ["Indonesien"],
        "98": ["Iran"],
        "964": ["Irak"],
        "353": ["Irland"],
        "972": ["Israel"],
        "39": ["Italien"],
        "1876": ["Jamaika"],
        "81": ["Japan"],
        "254": ["Kenia"],
        "996": ["Kirgisistan"],
        "856": ["Laos"],
        "371": ["Lettland"],
        "961": ["Libanon"],
        "266": ["Lesotho"],
        "231": ["Liberia"],
        "218": ["Libyen"],
        "423": ["Liechtenstein"],
        "370": ["Litauen"],
        "352": ["Luxemburg"],
        "389": ["Nordmazedonien"],
        "261": ["Madagaskar"],
        "60": ["Malaysia"],
        "356": ["Malta"],
        "52": ["Mexiko"],
        "373": ["Moldawien"],
        "377": ["Monaco"],
        "976": ["Mongolei"],
        "382": ["Montenegro"],
        "212": ["Marokko"],
        "95": ["Myanmar"],
        "264": ["Namibia"],
        "977": ["Nepal"],
        "31": ["Niederlande"],
        "64": ["Neuseeland"],
        "505": ["Nicaragua"],
        "227": ["Niger"],
        "234": ["Nigeria"],
        "47": ["Norwegen"],
        "92": ["Pakistan"],
        "507": ["Panama"],
        "675": ["Papua-Neuguinea"],
        "595": ["Paraguay"],
        "51": ["Peru"],
        "63": ["Philippinen"],
        "48": ["Polen"],
        "351": ["Portugal"],
        "40": ["Rumänien"],
        "7": ["Russland", "Kasachstan"],
        "378": ["San Marino"],
        "966": ["Saudi-Arabien"],
        "221": ["Senegal"],
        "381": ["Serbien"],
        "248": ["Seychellen"],
        "65": ["Singapur"],
        "421": ["Slowakei"],
        "386": ["Slowenien"],
        "677": ["Salomonen"],
        "252": ["Somalia"],
        "27": ["Südafrika"],
        "82": ["Südkorea"],
        "211": ["Südsudan"],
        "34": ["Spanien"],
        "94": ["Sri Lanka"],
        "249": ["Sudan"],
        "597": ["Suriname"],
        "268": ["Eswatini"],
        "46": ["Schweden"],
        "41": ["Schweiz"],
        "963": ["Syrien"],
        "886": ["Taiwan"],
        "992": ["Tadschikistan"],
        "255": ["Tansania"],
        "66": ["Thailand"],
        "216": ["Tunesien"],
        "90": ["Türkei"],
        "993": ["Turkmenistan"],
        "256": ["Uganda"],
        "380": ["Ukraine"],
        "971": ["Vereinigte Arabische Emirate"],
        "44": ["Vereinigtes Königreich"],
        "1": ["Vereinigte Staaten", "Puerto Rico", "Kanada"],
        "598": ["Uruguay"],
        "998": ["Usbekistan"],
        "58": ["Venezuela"],
        "84": ["Vietnam"],
        "967": ["Jemen"],
        "260": ["Sambia"],
        "263": ["Zimbabwe", "Simbabwe"],
        "357": ["Zypern"]
    },

    "countryToDomain": {
        "Deutschland": [".de"],
        "USA": [".us"],
        "Frankreich": [".fr"],
        "Japan": [".jp"],
        "Indien": [".in"]
    },
    "domainToCountry": {
        ".de": ["Deutschland"],
        ".us": ["USA", "Amerika", "Vereinigte Staaten"],
        ".fr": ["Frankreich"],
        ".jp": ["Japan"],
        ".in": ["Indien"]
    }
};